version: '3.4'

services:
  watcher:
    container_name: watcher
    build:
      context: ./watcher
      dockerfile: Dockerfile
    restart: "on-failure"
    depends_on:
      - postgres
      - logstash
 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      
  logstash:
    container_name: logstash
    build:
      context: logstash
      dockerfile: Dockerfile
    restart: "unless-stopped"
    depends_on:
      - elasticsearch
    environment:
      - CAP_ELK_APP_ID
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "9253:9253"
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.1
    restart: "unless-stopped"
    env_file: .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_BASEPATH=
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
 
  postgres:
    image: postgres:11.6-alpine
    container_name: postgres
    restart: "unless-stopped"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LANG=ru_RU.utf8
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  elasticsearch-data:
